### ISSUE TITLE
Token Capitalization option no longer available when adding/editing classifications

### ISSUE THREAD

**Issue by MrClyfar** [omsharp/docomment-progress#10]
Version 0.6

Just noticed that the `Token Capitalization` option is no longer available when I add, or edit, classifications...

![image](https://user-images.githubusercontent.com/700064/86893867-2c8cbf80-c0fa-11ea-89fc-6c10d6581296.png)

However, capitalization settings are still shown on the classifications list...

![image](https://user-images.githubusercontent.com/700064/86893952-48906100-c0fa-11ea-913f-6086c87eb338.png)

To be honest, this is not a feature that I used much, so if it was removed then it would not be something I'd miss. The only thing thing though, is that the comments I enter using the classifications are shown in lowercase, even though I did not type them like that...

![image](https://user-images.githubusercontent.com/700064/86894143-8f7e5680-c0fa-11ea-8142-e1042f36faf0.png)

In the above example, the word `Should` in the comment is shown as `should` in the Bookmarks List.

**Comment by omsharp** [comment]
@MrClyfar 

Token Capitalization and Application Style options were never implemented, I just forgot to remove them from the settings UI.

Token Capitalization was an old idea, before I even think of adornments, and now it doesn't make any sense to keep it, because the token is never shown anyway. Maybe I'll implement Application Style in the future. I'm not sure yet.

Anyway, both of them are removed now, from the form and the list.

**Comment by omsharp** [comment]
I can't reproduce this issue on my machine. Not sure if it was something solved in a newer version and I'm not aware of, or something else.

Does it occur with all bookmarks? Or just certain ones?


![image](https://user-images.githubusercontent.com/1245060/87255443-0c0e8d80-c48b-11ea-888a-c81046d9be82.png)

**Comment by MrClyfar** [comment]
In version 0.8.1 it looks like the first letter uppercase issue has been resolved.

Thanks for clarifying the situation with the token capitalization, that makes sense.
