### ISSUE TITLE
Incorrect classification entry appears in Bookmarks List.

### ISSUE THREAD

**Issue by MrClyfar** [omsharp/docomment-progress#6]
I added a new comment using the `BUG` classification into the source code file.

When I pressed the refresh on the Bookmarks List, with `BUG` as the selected classification, the comment for `Test-Compression` appears instead, not the `BUG` comment that I originally entered.

![image](https://user-images.githubusercontent.com/700064/86445802-f078e980-bd0a-11ea-8e08-1439e87b1d08.png)

When I change the Bookmarks List to show `Any` classifications, and press the refresh button, not all of the comments appear in the list.

![image](https://user-images.githubusercontent.com/700064/86446408-d2f84f80-bd0b-11ea-849e-bc4bf067a2b6.png)

**Comment by MrClyfar** [comment]
I tested this in version 0.4 and it still happens.

I think it might have something to do with the casing of the classification. check out this gif...

I create two classifications, one named `BUG` and another named `lowercase`.

When I create a comment using `BUG` it does not appear in the bookmarks list. But a comment created using the `lowercase` classification does appear in the list.


![Uppercase Classification Not Shown In Bookmraks List](https://user-images.githubusercontent.com/700064/86628323-a8372100-bfc1-11ea-8b17-0f6af12bd9cd.gif)

**Comment by omsharp** [comment]
@MrClyfar 
Yes indeed. It has to do with the casing of the token. Hopefully will be fixed on v0.6.

Thanks for the gif :)

**Comment by omsharp** [comment]
By the way, Token Capitalization and Application Style options are not implemented, I forgot to remove them from the form before publishing the extension. So both of them are removed from the form in v0.6.

Token Capitalization was an old idea and it doesn't make any sense to keep it, because the token is never shown anyway. 

Maybe I'll implement Application Style in the future. I'm not sure yet.
